# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: quit loafing around
# this will appear in your document head meta (for Google search results) and in your feed.xml site description.
description: >-
  stuff from my baking notebook. mostly bread. not only though. but mostly.

author: eliran malka
#email: eliranmal@gmail.com

# if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
domain: eliranmal.github.io
# the base hostname & protocol for your site, e.g. http://example.com
url: https://eliranmal.github.io
# the subpath of your site, e.g. /blog
baseurl: /quit-loafing-around

# output URLs without file extensions
permalink: pretty

# show post excerpts in the list
show_excerpts: true
# use this in posts to end the excerpt stanza
excerpt_separator: <!-- read more... -->

# show page links in the header menu
header_pages:
  - about.markdown

sass:
  # possible values: nested expanded compact compressed
  style: compact


# build settings
theme: minima
plugins:
  - jekyll-feed

exclude:
  - README.md

# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# The following items will not be processed, by default:
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

